### ISSUE TITLE
画面中央部に表示させるための画像の設定

### ISSUE THREAD

**Issue by suzukin** [vscodejp/conf2021#5]
イベント用のロゴ、元データは[こちら](https://drive.google.com/drive/u/0/folders/1w0VvXjyXo7rrFP9yNvugB2wf5rF0yHo7) aiの加工が必要な場合は @azusa に要相談！

![](https://connpass-tokyo.s3.amazonaws.com/thumbs/c6/82/c682e8de952de441c013fec222ee1263.png)

**Comment by jiyuujin** [comment]
@azusa さんに作成いただきました mm

https://vscodemeetup.slack.com/archives/C02321T7KPH/p1630275384009400
